apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: team-data-nodepool
spec:
  disruption:
    consolidateAfter: 15s
    consolidationPolicy: WhenEmpty
    budgets:
      - nodes: "100%"
  limits:
    cpu: "50"
  template:
    metadata:
      labels:
        # required for Karpenter to predict overhead from cilium DaemonSet
        kubernetes.azure.com/ebpf-dataplane: cilium
        aks-karpenter: demo-team
    spec:
      nodeClassRef:
        group: karpenter.azure.com
        kind: AKSNodeClass
        name: default-demo
      startupTaints:
        # https://karpenter.sh/docs/concepts/nodepools/#cilium-startup-taint
        - key: node.cilium.io/agent-not-ready
          effect: NoExecute
          value: "true"
      taints:
        - key: microsoft.com/team
          value: "team-data"
          effect: NoSchedule
      requirements:
        - key: karpenter.azure.com/sku-family
          operator: In
          values: [D]
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.azure.com/sku-cpu
          operator: Lt
          values: ["16"]
        - key: microsoft.com/team
          operator: In
          values: ["team-data"]
      expireAfter: Never
