apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate-noteam
  namespace: workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inflate-team
  template:
    metadata:
      labels:
        app: inflate-team
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: karpenterossazuredemo.azurecr.io/pause:3.7
          resources:
            requests:
              cpu: 1
      nodeSelector:
        aks-karpenter: demo-team